### ISSUE TITLE
various small feedback for llamasearch

### ISSUE THREAD

**Issue by asnogordo** [0xngmi/llamasearch#3]
Love the idea of your tool, ran into a few issues and wanted to give feedback.

cowswap was one of the first things that I wanted to search in the tool.

1. 'cow' yielded nothing - I looked at the code and saw your >3 char limit. I can see why you did that, but it might be worth playing around with making that >2 (perhaps its too noisy).

2. $cow yields both cashcow and cow(cowswap) without any way to distinguish them. One suggestion there would be to include the token symbol in the output.

3. 'cows' only yields the bnb cowswap which has a much lower mc. In cases like this I think market cap could help with sorting order.
![image](https://github.com/0xngmi/llamasearch/assets/1376034/777f1fb0-c3bf-49be-8ac3-4da95507c8ac)

4. autocomplete on brave blocks your autocomplete. Might just be an issue with Brave, but wanted to raise it. Adding _autocomplete="off"_ to the input fixes it for me in testing.

![llamasearch_autocomplete](https://github.com/0xngmi/llamasearch/assets/1376034/9f3e9a80-c0b2-4543-960a-ab783e62422a)

Other Ideas:
I am sure you want to keep the UX simple, similar to Google, but it would be cool if there was an option to enable an eth gas number/chart at the top right (or really anywhere) just to get a quick glance at the current state of gas
![image](https://github.com/0xngmi/llamasearch/assets/1376034/30b85946-1e70-4bbc-a356-7bd80e8a62c4)

**Comment by 0xngmi** [comment]
ty for the feedback

1. i tried with >2 and it was not very helpful
2. i guess you meant token name? good idea
3. rn its sorting by tvl but youre right that its not great for protocols with no tvl like cowswap hmm
4. agree
5. (gas cost) agree

**Comment by 0xngmi** [comment]
2, 3, 4 implemented

**Comment by asnogordo** [comment]
Thanks for the review. You got the main stuff, and I'll open another issue if anything comes up.
